### ISSUE TITLE
Perfect scrollbar

### ISSUE THREAD

**Issue by marc-gist** [creativetimofficial/ct-now-ui-dashboard-pro#59] opened 2019-01-26 14:19 UTC
scrollbar on side bar when minimzed issue is back.
also, had to change js code (or add IDs to HTML) as your docs state

> !IMPORTANT Perfect Scrollbar is applied on the .main-panel and .sidebar .sidebar-wrapper so we will have a nice scrollbar that is visible only 

but in the JS code its using IDs not classes

    const ps = new PerfectScrollbar('#sidebar-wrapper');
    const ps2 = new PerfectScrollbar('#main-panel');

**Comment by dragosct** [comment] 2019-01-28 10:31
Hi! Please tell us more details about this issue or send us some screenshots. Regard to the code you are right we must change also that text from the docs thank you for this observation. 

Regards, 
Dragos

**Comment by Boneless117** [comment] 2019-02-03 04:03
The issue is in line 52 - 64 within the 'now-ui-dashbaord.js' file.
(assets/js/now-ui-dashbaord.js)
The error is stating that perfect scrollbar is expecting a Class, yet an ID is given.

Following the above suggestion:
**Change**
```
const ps = new PerfectScrollbar('#sidebar-wrapper');
const ps2 = new PerfectScrollbar('#main-panel');
```

**To**
```
const ps = new PerfectScrollbar('.sidebar-wrapper');
const ps2 = new PerfectScrollbar('.main-panel');
```
This resolved one issue for me.

Also, I noticed that perfectscrollbar was adding white spaces around things unexpectedly.
I resolved this by adding the css file from the PerfectScrollbar plugin: 
[HERE](https://github.com/utatti/perfect-scrollbar/blob/master/css/perfect-scrollbar.css)

**Comment by dragosct** [comment] 2019-02-04 08:10
Hi, @Boneless117! Thank you for this. We will change this in the next update. 

Regards, 
Dragos

**Comment by lostmagicK** [comment] 2019-03-11 07:46
![image](https://user-images.githubusercontent.com/35366477/54107634-baba3e00-43ff-11e9-8090-3c77b0855f1b.png)
Scrollbar issue I tried solution provided by @Boneless117 but scrollbar is still a issue

**Comment by dragosct** [comment] 2019-03-11 07:48
Hi, @lostmagicK! Thank you for using our products. Please tell us if you add also the CSS for the perfect-scrollbar? 

Regards, 
Dragos

**Comment by lostmagicK** [comment] 2019-03-11 08:45
Yes I did
    <script src="~/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>

**Comment by lostmagicK** [comment] 2019-03-11 08:49
I didnt find any css for perfect-scrollbar in files provided

**Comment by dragosct** [comment] 2019-03-11 08:51
Hi! Please read more carefully the message from above and you will see that there you will find a link named `HERE` and there it's the CSS that you need. 

Regards,
Dragos

**Comment by lostmagicK** [comment] 2019-03-11 08:56
That did work thanks.. :D

**Comment by Hansander** [comment] 2019-05-17 07:53
Hi Dragos,

This issue still persists, I tested it on Both Chrome and Firefox (works on Linux breaks on Windows 10), the live demo online also has the same error 
`Uncaught TypeError: $(...).perfectScrollbar is not a function
    at HTMLDivElement.<anonymous> (<anonymous>:1:1759)
    at HTMLDivElement.dispatch (<anonymous>:2:41772)
    at HTMLDivElement.y.handle (<anonymous>:2:39791)
    at Object.trigger (<anonymous>:2:69551)
    at HTMLDivElement.<anonymous> (<anonymous>:2:70146)
    at Function.each (<anonymous>:2:2573)
    at w.fn.init.each (<anonymous>:2:1240)
    at w.fn.init.trigger (<anonymous>:2:70122)
    at o.t.show (<anonymous>:6:26492)
    at HTMLDivElement.<anonymous> (<anonymous>:6:33132)`

It happens on trying to open a modal on the notifications page.   The error is between, lines 101 and 115 in the now-ui-dashboard.js file.

I did an experiment where I exchanged the perfectscroll.min.js from material dashboard pro with the one in nowui, to see if the issue would resolve, it did, but then the sidebar-mini toggle failed, so the issue might be inside the perfectscroll file itself.  Please advise

**Comment by dragosct** [comment] 2019-05-20 06:38
Hi, @Hansander! Thank you for using our products. Did you try to follow the steps below in order to fix this issue? 

Regards, 
Dragos

**Comment by jposes22** [comment] 2019-06-01 20:31
Same problem here!! 
Our problem is worst with this issue modal doesn´t work too.
If you put  <script th:src="@{/assets/js/now-ui-dashboard.js?v=1.4.0}"></script> then doesnt work modals.
Same on linux, OSX and mobile browser works fine but in windows 10 fails.

**Comment by dragosct** [comment] 2019-06-03 06:50
Hi, @jposes22! I think the problem that you have with the modals it's related to the perfect scrollbar because we put on windows 10 when the modal it's open to activate also the perfect scrollbar for modals, so please see above the steps to make the perfect scrollbar to work. 

Regards, 
Dragos

**Comment by Hansander** [comment] 2019-06-03 06:59
Hi Dragos,

I did the steps below and ended up stripping the perfect scrollbar out alltogether.  The concern that I have is that is seems like the perfect scrollbar project has been abandoned, looking at the github repo for this.  If you look at the demo online, you will see that the scrollbars look BAD.  I took this screenshot from Chrome inside Linux.
Something is not right with the scrollbars, using the demo on your site as an example.

![image](https://user-images.githubusercontent.com/29998695/58781984-a3918380-85dd-11e9-83d4-0acc5d163efd.png)

**Comment by dragosct** [comment] 2019-06-05 07:57
Hi, @Hansander! We will make an update for the product by the end of this week and then it will look fine. 

Regards,
Dragos

**Comment by dragosct** [comment] 2019-06-07 10:00
The update was made. We will close the issue! 

Regards,
Dragos

**Closed as completed by dragosct** 2019-06-07 10:00 UTC
Labels: bug, help wanted

**Comment by Devanshi1728** [comment] 2021-03-05 08:21
I still have PerfectScrollBar error..i have added css file from here but still i gives error of same
